version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.3-debian-11-r43'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.0.1'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_DELETE_TOPIC_ENABLE=false
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKAJS_DEBUG_PROTOCOL_BUFFERS=1
    depends_on:
      - zookeeper